knpu_oauth2_client:
    clients:
        # will create service: "knpu.oauth2.client.foo_bar_oauth"
        # an instance of: KnpU\OAuth2ClientBundle\Client\OAuth2Client
        zenodo_main:
            type: generic
            provider_class: App\Provider\Zenodo

            # optional: a class that extends OAuth2Client
            # client_class: Some\Custom\Client

            # optional: if your provider has custom constructor options
            # provider_options: {}

            # now, all the normal options!
            client_id: ''
            client_secret: ''
            redirect_route: connect_zenodo_check
            redirect_params: {}
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
