home:
    path: /{_locale<en|fr>}/home
    controller: App\Controller\HomeController::index

login:
    path: /{_locale<en|fr>}/login
    controller: App\Controller\LoginController::loginAction

force:
    path: /{_locale<en|fr>}/force
    controller: App\Controller\LoginController::force

logout:
    path: /{_locale<en|fr>}/logout
    controller: App\Controller\LoginController::logoutAction

create_deposit:
    path: /{_locale<en|fr>}/deposit
    controller: App\Controller\DepositController::new

edit_deposit:
    path:  /{_locale<en|fr>}/deposit/{id}/edit
    controller: App\Controller\DepositController::edit
delete_file:
    path: /deposit/{id}/delete/file/{fileId}
    controller: App\Controller\DepositController::deleteFile